apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  name: gateways.networking.istio.io
spec:
  group: networking.istio.io
  names:
    categories:
      - istio-io
      - networking-istio-io
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    shortNames:
      - gw
    singular: gateway
  scope: Namespaced
  versions:
    - name: v1alpha3
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec"
              properties:
                selector:
                  additionalProperties:
                    type: string
                  type: object
                servers:
                  description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers"
                  items:
                    properties:
                      bind:
                        type: string
                      defaultEndpoint:
                        type: string
                      hosts:
                        description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.hosts"
                        items:
                          type: string
                        type: array
                      name:
                        description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.name"
                        type: string
                      port:
                        properties:
                          name:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.name"
                            type: string
                          number:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.number"
                            type: integer
                          protocol:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.protocol"
                            type: string
                          targetPort:
                            type: integer
                        type: object
                      tls:
                        description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls"
                        properties:
                          caCertificates:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.caCertificates"
                            type: string
                          cipherSuites:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.cipherSuites"
                            items:
                              type: string
                            type: array
                          credentialName:
                            type: string
                          httpsRedirect:
                            type: boolean
                          maxProtocolVersion:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.maxProtocolVersion"
                            enum:
                              - TLS_AUTO
                              - TLSV1_0
                              - TLSV1_1
                              - TLSV1_2
                              - TLSV1_3
                            type: string
                          minProtocolVersion:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.minProtocolVersion"
                            enum:
                              - TLS_AUTO
                              - TLSV1_0
                              - TLSV1_1
                              - TLSV1_2
                              - TLSV1_3
                            type: string
                          mode:
                            enum:
                              - PASSTHROUGH
                              - SIMPLE
                              - MUTUAL
                              - AUTO_PASSTHROUGH
                              - ISTIO_MUTUAL
                            type: string
                          privateKey:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.privateKey"
                            type: string
                          serverCertificate:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.serverCertificate"
                            type: string
                          subjectAltNames:
                            items:
                              type: string
                            type: array
                          verifyCertificateHash:
                            items:
                              type: string
                            type: array
                          verifyCertificateSpki:
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  type: array
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
    - name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec"
              properties:
                selector:
                  additionalProperties:
                    type: string
                  type: object
                servers:
                  description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers"
                  items:
                    properties:
                      bind:
                        type: string
                      defaultEndpoint:
                        type: string
                      hosts:
                        description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.hosts"
                        items:
                          type: string
                        type: array
                      name:
                        description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.name"
                        type: string
                      port:
                        properties:
                          name:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.name"
                            type: string
                          number:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.number"
                            type: integer
                          protocol:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.port.properties.protocol"
                            type: string
                          targetPort:
                            type: integer
                        type: object
                      tls:
                        description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls"
                        properties:
                          caCertificates:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.caCertificates"
                            type: string
                          cipherSuites:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.cipherSuites"
                            items:
                              type: string
                            type: array
                          credentialName:
                            type: string
                          httpsRedirect:
                            type: boolean
                          maxProtocolVersion:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.maxProtocolVersion"
                            enum:
                              - TLS_AUTO
                              - TLSV1_0
                              - TLSV1_1
                              - TLSV1_2
                              - TLSV1_3
                            type: string
                          minProtocolVersion:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.minProtocolVersion"
                            enum:
                              - TLS_AUTO
                              - TLSV1_0
                              - TLSV1_1
                              - TLSV1_2
                              - TLSV1_3
                            type: string
                          mode:
                            enum:
                              - PASSTHROUGH
                              - SIMPLE
                              - MUTUAL
                              - AUTO_PASSTHROUGH
                              - ISTIO_MUTUAL
                            type: string
                          privateKey:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.privateKey"
                            type: string
                          serverCertificate:
                            description: "%gateways.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.servers.items.properties.tls.properties.serverCertificate"
                            type: string
                          subjectAltNames:
                            items:
                              type: string
                            type: array
                          verifyCertificateHash:
                            items:
                              type: string
                            type: array
                          verifyCertificateSpki:
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  type: array
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: false
      subresources:
        status: {}
