apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    istio: security
    release: istio
  name: requestauthentications.security.istio.io
spec:
  group: security.istio.io
  names:
    categories:
      - istio-io
      - security-istio-io
    kind: RequestAuthentication
    listKind: RequestAuthenticationList
    plural: requestauthentications
    shortNames:
      - ra
    singular: requestauthentication
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec"
              properties:
                jwtRules:
                  description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.jwtRules"
                  items:
                    properties:
                      audiences:
                        items:
                          type: string
                        type: array
                      forwardOriginalToken:
                        description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.jwtRules.items.properties.forwardOriginalToken"
                        type: boolean
                      fromHeaders:
                        description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.jwtRules.items.properties.fromHeaders"
                        items:
                          properties:
                            name:
                              description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.jwtRules.items.properties.fromHeaders.items.properties.name"
                              type: string
                            prefix:
                              description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.jwtRules.items.properties.fromHeaders.items.properties.prefix"
                              type: string
                          type: object
                        type: array
                      fromParams:
                        description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.jwtRules.items.properties.fromParams"
                        items:
                          type: string
                        type: array
                      issuer:
                        description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.jwtRules.items.properties.issuer"
                        type: string
                      jwks:
                        description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.jwtRules.items.properties.jwks"
                        type: string
                      jwks_uri:
                        type: string
                      jwksUri:
                        type: string
                      outputPayloadToHeader:
                        type: string
                    type: object
                  type: array
                selector:
                  description: "%requestauthentications.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.selector"
                  properties:
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
