apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  name: serviceentries.networking.istio.io
spec:
  group: networking.istio.io
  names:
    categories:
      - istio-io
      - networking-istio-io
    kind: ServiceEntry
    listKind: ServiceEntryList
    plural: serviceentries
    shortNames:
      - se
    singular: serviceentry
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The hosts associated with the ServiceEntry
          jsonPath: .spec.hosts
          name: Hosts
          type: string
        - description: Whether the service is external to the mesh or part of the mesh
            (MESH_EXTERNAL or MESH_INTERNAL)
          jsonPath: .spec.location
          name: Location
          type: string
        - description: Service discovery mode for the hosts (NONE, STATIC, or DNS)
          jsonPath: .spec.resolution
          name: Resolution
          type: string
        - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha3
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec"
              properties:
                addresses:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.addresses"
                  items:
                    type: string
                  type: array
                endpoints:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints"
                  items:
                    properties:
                      address:
                        type: string
                      labels:
                        additionalProperties:
                          type: string
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints.items.properties.labels"
                        type: object
                      locality:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints.items.properties.locality"
                        type: string
                      network:
                        type: string
                      ports:
                        additionalProperties:
                          type: integer
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints.items.properties.ports"
                        type: object
                      serviceAccount:
                        type: string
                      weight:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints.items.properties.weight"
                        type: integer
                    type: object
                  type: array
                exportTo:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.exportTo"
                  items:
                    type: string
                  type: array
                hosts:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.hosts"
                  items:
                    type: string
                  type: array
                location:
                  enum:
                    - MESH_EXTERNAL
                    - MESH_INTERNAL
                  type: string
                ports:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ports"
                  items:
                    properties:
                      name:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ports.items.properties.name"
                        type: string
                      number:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ports.items.properties.number"
                        type: integer
                      protocol:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ports.items.properties.protocol"
                        type: string
                      targetPort:
                        type: integer
                    type: object
                  type: array
                resolution:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.resolution"
                  enum:
                    - NONE
                    - STATIC
                    - DNS
                    - DNS_ROUND_ROBIN
                  type: string
                subjectAltNames:
                  items:
                    type: string
                  type: array
                workloadSelector:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.workloadSelector"
                  properties:
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
    - additionalPrinterColumns:
        - description: The hosts associated with the ServiceEntry
          jsonPath: .spec.hosts
          name: Hosts
          type: string
        - description: Whether the service is external to the mesh or part of the mesh
            (MESH_EXTERNAL or MESH_INTERNAL)
          jsonPath: .spec.location
          name: Location
          type: string
        - description: Service discovery mode for the hosts (NONE, STATIC, or DNS)
          jsonPath: .spec.resolution
          name: Resolution
          type: string
        - description: 'CreationTimestamp is a timestamp representing the server time
        when this object was created. It is not guaranteed to be set in happens-before
        order across separate operations. Clients may not set this value. It is represented
        in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
        lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec"
              properties:
                addresses:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.addresses"
                  items:
                    type: string
                  type: array
                endpoints:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints"
                  items:
                    properties:
                      address:
                        type: string
                      labels:
                        additionalProperties:
                          type: string
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints.items.properties.labels"
                        type: object
                      locality:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints.items.properties.locality"
                        type: string
                      network:
                        type: string
                      ports:
                        additionalProperties:
                          type: integer
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints.items.properties.ports"
                        type: object
                      serviceAccount:
                        type: string
                      weight:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.endpoints.items.properties.weight"
                        type: integer
                    type: object
                  type: array
                exportTo:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.exportTo"
                  items:
                    type: string
                  type: array
                hosts:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.hosts"
                  items:
                    type: string
                  type: array
                location:
                  enum:
                    - MESH_EXTERNAL
                    - MESH_INTERNAL
                  type: string
                ports:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ports"
                  items:
                    properties:
                      name:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ports.items.properties.name"
                        type: string
                      number:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ports.items.properties.number"
                        type: integer
                      protocol:
                        description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ports.items.properties.protocol"
                        type: string
                      targetPort:
                        type: integer
                    type: object
                  type: array
                resolution:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.resolution"
                  enum:
                    - NONE
                    - STATIC
                    - DNS
                    - DNS_ROUND_ROBIN
                  type: string
                subjectAltNames:
                  items:
                    type: string
                  type: array
                workloadSelector:
                  description: "%serviceentries.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.workloadSelector"
                  properties:
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: false
      subresources:
        status: {}
