apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  name: sidecars.networking.istio.io
spec:
  group: networking.istio.io
  names:
    categories:
      - istio-io
      - networking-istio-io
    kind: Sidecar
    listKind: SidecarList
    plural: sidecars
    singular: sidecar
  scope: Namespaced
  versions:
    - name: v1alpha3
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec"
              properties:
                egress:
                  items:
                    properties:
                      bind:
                        type: string
                      captureMode:
                        enum:
                          - DEFAULT
                          - IPTABLES
                          - NONE
                        type: string
                      hosts:
                        items:
                          type: string
                        type: array
                      port:
                        description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.egress.items.properties.port"
                        properties:
                          name:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.name"
                            type: string
                          number:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.number"
                            type: integer
                          protocol:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.protocol"
                            type: string
                          targetPort:
                            type: integer
                        type: object
                    type: object
                  type: array
                ingress:
                  items:
                    properties:
                      bind:
                        description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.bind"
                        type: string
                      captureMode:
                        enum:
                          - DEFAULT
                          - IPTABLES
                          - NONE
                        type: string
                      defaultEndpoint:
                        type: string
                      port:
                        description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port"
                        properties:
                          name:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.name"
                            type: string
                          number:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.number"
                            type: integer
                          protocol:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.protocol"
                            type: string
                          targetPort:
                            type: integer
                        type: object
                      tls:
                        properties:
                          caCertificates:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.caCertificates"
                            type: string
                          cipherSuites:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.cipherSuites"
                            items:
                              type: string
                            type: array
                          credentialName:
                            type: string
                          httpsRedirect:
                            type: boolean
                          maxProtocolVersion:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.maxProtocolVersion"
                            enum:
                              - TLS_AUTO
                              - TLSV1_0
                              - TLSV1_1
                              - TLSV1_2
                              - TLSV1_3
                            type: string
                          minProtocolVersion:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.minProtocolVersion"
                            enum:
                              - TLS_AUTO
                              - TLSV1_0
                              - TLSV1_1
                              - TLSV1_2
                              - TLSV1_3
                            type: string
                          mode:
                            enum:
                              - PASSTHROUGH
                              - SIMPLE
                              - MUTUAL
                              - AUTO_PASSTHROUGH
                              - ISTIO_MUTUAL
                            type: string
                          privateKey:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.privateKey"
                            type: string
                          serverCertificate:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.serverCertificate"
                            type: string
                          subjectAltNames:
                            items:
                              type: string
                            type: array
                          verifyCertificateHash:
                            items:
                              type: string
                            type: array
                          verifyCertificateSpki:
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  type: array
                outboundTrafficPolicy:
                  description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy"
                  properties:
                    egressProxy:
                      properties:
                        host:
                          description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy.properties.egressProxy.properties.host"
                          type: string
                        port:
                          description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy.properties.egressProxy.properties.port"
                          properties:
                            number:
                              type: integer
                          type: object
                        subset:
                          description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy.properties.egressProxy.properties.subset"
                          type: string
                      type: object
                    mode:
                      enum:
                        - REGISTRY_ONLY
                        - ALLOW_ANY
                      type: string
                  type: object
                workloadSelector:
                  properties:
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
    - name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec"
              properties:
                egress:
                  items:
                    properties:
                      bind:
                        type: string
                      captureMode:
                        enum:
                          - DEFAULT
                          - IPTABLES
                          - NONE
                        type: string
                      hosts:
                        items:
                          type: string
                        type: array
                      port:
                        description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.egress.items.properties.port"
                        properties:
                          name:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.name"
                            type: string
                          number:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.number"
                            type: integer
                          protocol:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.egress.items.properties.port.properties.protocol"
                            type: string
                          targetPort:
                            type: integer
                        type: object
                    type: object
                  type: array
                ingress:
                  items:
                    properties:
                      bind:
                        description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.bind"
                        type: string
                      captureMode:
                        enum:
                          - DEFAULT
                          - IPTABLES
                          - NONE
                        type: string
                      defaultEndpoint:
                        type: string
                      port:
                        description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port"
                        properties:
                          name:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.name"
                            type: string
                          number:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.number"
                            type: integer
                          protocol:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.port.properties.protocol"
                            type: string
                          targetPort:
                            type: integer
                        type: object
                      tls:
                        properties:
                          caCertificates:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.caCertificates"
                            type: string
                          cipherSuites:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.cipherSuites"
                            items:
                              type: string
                            type: array
                          credentialName:
                            type: string
                          httpsRedirect:
                            type: boolean
                          maxProtocolVersion:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.maxProtocolVersion"
                            enum:
                              - TLS_AUTO
                              - TLSV1_0
                              - TLSV1_1
                              - TLSV1_2
                              - TLSV1_3
                            type: string
                          minProtocolVersion:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.minProtocolVersion"
                            enum:
                              - TLS_AUTO
                              - TLSV1_0
                              - TLSV1_1
                              - TLSV1_2
                              - TLSV1_3
                            type: string
                          mode:
                            enum:
                              - PASSTHROUGH
                              - SIMPLE
                              - MUTUAL
                              - AUTO_PASSTHROUGH
                              - ISTIO_MUTUAL
                            type: string
                          privateKey:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.privateKey"
                            type: string
                          serverCertificate:
                            description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.ingress.items.properties.tls.properties.serverCertificate"
                            type: string
                          subjectAltNames:
                            items:
                              type: string
                            type: array
                          verifyCertificateHash:
                            items:
                              type: string
                            type: array
                          verifyCertificateSpki:
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  type: array
                outboundTrafficPolicy:
                  description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy"
                  properties:
                    egressProxy:
                      properties:
                        host:
                          description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy.properties.egressProxy.properties.host"
                          type: string
                        port:
                          description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy.properties.egressProxy.properties.port"
                          properties:
                            number:
                              type: integer
                          type: object
                        subset:
                          description: "%sidecars.yaml.spec.versions.schema.openAPIV3Schema.properties.spec.properties.outboundTrafficPolicy.properties.egressProxy.properties.subset"
                          type: string
                      type: object
                    mode:
                      enum:
                        - REGISTRY_ONLY
                        - ALLOW_ANY
                      type: string
                  type: object
                workloadSelector:
                  properties:
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: false
      subresources:
        status: {}
